In [231]:
import uproot
import pandas as pd

f = uproot.open("output.root")

# First tree is 'electrons'
tree = f[f.keys()[0]]
print(f"Tree: {f.keys()[0]}  ({tree.num_entries:.0f} entries)")
print("Branches:", tree.keys())

Tree: electrons;1  (294289 entries)
Branches: ['energy', 'x', 'y', 'z', 'edep', 'trackID', 'parentID', 'length', 'proc', 'runID']

In [232]:
df = tree.arrays(library="pd")
df = df[["runID","trackID","parentID", "proc","x", "y", "z", "edep", "length","energy"]]
df

,runID,trackID,parentID,proc,x,y,z,edep,length,energy
0,2,1.0,0.0,Ion1Process,-3.376852,-0.033104,100.056087,12.600000,100.056087,99948.458237
1,2,1.0,0.0,J3Process,-3.376852,-0.033104,100.076841,0.007800,100.076841,99948.450437
2,2,1.0,0.0,Ion2Process,-3.369747,-0.026364,100.637896,14.520000,100.637982,99923.510888
3,2,1.0,0.0,Ion2Process,-3.369298,-0.025938,100.673371,14.520000,100.673461,99897.760113
4,2,1.0,0.0,Ion1Process,-3.368874,-0.025536,100.706866,12.600000,100.706962,99878.018265
...,...,...,...,...,...,...,...,...,...,...
294284,10,4.0,1.0,Electron Killed,-2.122793,-0.342143,100.297214,7.020045,0.016874,0.000000
294285,10,4700.0,4.0,Electron Killed,-2.120675,-0.342057,100.297470,2.000000,0.000116,0.000000
294286,10,4699.0,4.0,Electron Killed,-2.118649,-0.341273,100.296753,2.000001,0.001951,0.000000
294287,10,3.0,1.0,Electron Killed,-2.118781,-0.342282,100.151371,3.078592,0.000335,0.000000
294288,10,2.0,1.0,Electron Killed,-2.118586,-0.342544,100.083282,3.049188,0.000031,0.000000

In [233]:
df.tail(10)

,runID,trackID,parentID,proc,x,y,z,edep,length,energy
294279,10,4.0,1.0,Nu4Process,-2.120392,-0.341506,100.297710,0.162000,0.003207,12.547045
294280,10,4.0,1.0,ND2Process,-2.120376,-0.341496,100.297720,4.950000,0.003229,7.597045
294281,10,4.0,1.0,Nu2Process,-2.121451,-0.341818,100.297828,0.190000,0.004504,7.407045
294282,10,4.0,1.0,Nu3Process,-2.121710,-0.341604,100.297409,0.374000,0.006081,7.033045
294283,10,4.0,1.0,J4Process,-2.122209,-0.341629,100.297627,0.013000,0.014221,7.020045
294284,10,4.0,1.0,Electron Killed,-2.122793,-0.342143,100.297214,7.020045,0.016874,0.000000
294285,10,4700.0,4.0,Electron Killed,-2.120675,-0.342057,100.297470,2.000000,0.000116,0.000000
294286,10,4699.0,4.0,Electron Killed,-2.118649,-0.341273,100.296753,2.000001,0.001951,0.000000
294287,10,3.0,1.0,Electron Killed,-2.118781,-0.342282,100.151371,3.078592,0.000335,0.000000
294288,10,2.0,1.0,Electron Killed,-2.118586,-0.342544,100.083282,3.049188,0.000031,0.000000

In [234]:
df.loc[df["proc"] == "Escape"]

Empty DataFrame
Columns: [runID, trackID, parentID, proc, x, y, z, edep, length, energy]
Index: []

In [235]:
df['edep'].sum()

np.float64(995773.3700000063)

In [236]:
tree_2 = f[f.keys()[1]]
df_2 = tree_2.arrays(library="pd")
df_2.rename(columns={"electronTrackID": "electronParentID"}, inplace=True)
df_2 = df_2[["runID","electronParentID", "particleName", "x", "y", "z", "globalTime_ns"]]

In [237]:
df_2

,runID,electronParentID,particleName,x,y,z,globalTime_ns
0,1,1.0,CH3+,-0.260685,-1.940937,100.083998,0.608959
1,1,1.0,H*,-0.260685,-1.940937,100.083998,0.608959
2,1,1.0,CH4+,-0.260496,-1.940938,100.094870,0.609026
3,1,1.0,CH3+,-0.260162,-1.940939,100.113989,0.609142
4,1,1.0,H*,-0.260162,-1.940939,100.113989,0.609142
...,...,...,...,...,...,...,...
129742,10,4.0,CH4+,-2.120561,-0.342033,100.297466,0.610741
129743,10,4.0,CH3*,-2.120570,-0.342077,100.297432,0.610764
129744,10,4.0,H*,-2.120570,-0.342077,100.297432,0.610764
129745,10,4.0,CH2*,-2.120376,-0.341496,100.297720,0.611406
129746,10,4.0,H2,-2.120376,-0.341496,100.297720,0.611406

In [238]:
tree_2 = f[f.keys()[2]]
df_3 = tree_2.arrays(library="pd")

df_3 = df_3[["runID","x", "y", "z", "energy",  "globalTime_ns"]]

In [239]:
df_3['energy'].sum() + df['edep'].sum() - 1000000

np.float64(6.28642737865448e-09)

In [240]:
df_3

     runID         x         y           z  energy  globalTime_ns
0        1  0.825618  0.316738  127.159466    2.86       0.778632
1        1 -0.308354  1.279848  149.446667    2.88       0.923936
2        1 -0.510034  1.292113  153.334230    1.89       0.949707
3        1 -0.783434  1.509545  161.615685    1.89       1.005312
4        1 -0.915635  1.437679  165.542445    2.88       1.032094
..     ...       ...       ...         ...     ...            ...
678     10  0.578540 -1.045048  148.901649   10.20       0.917626
679     10 -0.387751 -1.578568  136.573227   12.08       0.837887
680     10 -0.783931 -0.574404  117.561406    2.88       0.717370
681     10 -0.905719 -0.503204  116.192481    2.88       0.708287
682     10 -1.047769 -0.393201  114.630066   10.20       0.699682

[683 rows x 6 columns]